export interface Review {
  id: string;
  productName: string;
  productSlug: string;
  rating: number;
  customerName: string;
  location: string;
  date: string;
  title: string;
  body: string;
  verified: boolean;
  helpful: number;
}

export const reviews: Review[] = [
  {
    id: "rev-001",
    productName: "Saguaro (Carnegiea gigantea) Seed Pack",
    productSlug: "saguaro-seed-pack",
    rating: 5,
    customerName: "Maria G.",
    location: "Phoenix, AZ",
    date: "2025-11-14",
    title: "Germination was incredible",
    body: "I've ordered from three different seed banks over the years and these are by far the freshest saguaro seeds I've ever handled. Planted 30 seeds, got 28 seedlings within two weeks. The growing guide that came with the pack was genuinely useful — not just generic boilerplate. Already planning my next order.",
    verified: true,
    helpful: 47,
  },
  {
    id: "rev-002",
    productName: "Peyote (Lophophora williamsii) Seeds",
    productSlug: "peyote-lophophora-williamsii",
    rating: 5,
    customerName: "Daniel K.",
    location: "Austin, TX",
    date: "2025-12-03",
    title: "Healthy germination, great quality",
    body: "Was nervous ordering these online but the seeds arrived vacuum-sealed with a moisture pack. Germinated about 85% of them on a standard cactus mix. They're now 3 months old and looking strong. Discreet packaging too — appreciated the care.",
    verified: true,
    helpful: 33,
  },
  {
    id: "rev-003",
    productName: "San Pedro (Trichocereus pachanoi) Seeds",
    productSlug: "san-pedro-seed-pack",
    rating: 5,
    customerName: "Elijah W.",
    location: "Denver, CO",
    date: "2025-10-22",
    title: "Fast shipping, even faster germination",
    body: "Ordered on Monday, arrived Wednesday. The seeds sprouted within 5 days under a basic grow light. These San Pedro seeds are vigorous — already pushing out their second set of true leaves. Will definitely be back for more varieties.",
    verified: true,
    helpful: 29,
  },
  {
    id: "rev-004",
    productName: "Barrel Cactus (Echinocactus) Mix Seeds",
    productSlug: "barrel-cactus-mix",
    rating: 4,
    customerName: "Sarah L.",
    location: "Tucson, AZ",
    date: "2025-09-18",
    title: "Nice variety in the mix",
    body: "Love getting a mix — some golden barrel, some fishhook barrel, a few I couldn't even identify. About 75% germination which is solid for a wild mix. My only note is the pack could be a bit larger for the price. But the quality is there.",
    verified: true,
    helpful: 18,
  },
  {
    id: "rev-005",
    productName: "Mammillaria (Powder Puff) Seed Mix",
    productSlug: "mammillaria-seed-mix",
    rating: 5,
    customerName: "Rebecca T.",
    location: "Portland, OR",
    date: "2025-11-01",
    title: "My kids love watching them grow",
    body: "Bought these as a family project and they've been amazing. The seedlings are fuzzy and adorable — my 7-year-old checks on them every morning. Great germination rate and the instructions were clear enough for a complete beginner. Already ordered the succulent mix for our next project.",
    verified: true,
    helpful: 41,
  },
  {
    id: "rev-006",
    productName: "String of Pearls (Senecio rowleyanus) Seeds",
    productSlug: "string-of-pearls-seeds",
    rating: 5,
    customerName: "Jess M.",
    location: "Brooklyn, NY",
    date: "2025-12-10",
    title: "Finally got these to sprout",
    body: "I've killed two store-bought String of Pearls plants. Decided to try from seed with proper guidance and it worked. The seeds are tiny but viable — got about 60% germination. Now they're cascading beautifully from a hanging planter. The growing guide tips on light exposure were spot-on.",
    verified: true,
    helpful: 37,
  },
  {
    id: "rev-007",
    productName: "Lithops (Living Stones) Mixed Seeds",
    productSlug: "lithops-living-stones",
    rating: 5,
    customerName: "Tom H.",
    location: "Seattle, WA",
    date: "2025-10-05",
    title: "These are magical",
    body: "Lithops are genuinely fascinating plants. The seeds germinated easily and the seedlings look like tiny green candies. They're now splitting for the first time and I'm mesmerized. The mix includes several different species so you get a nice variety of patterns. Highly recommend for anyone interested in unusual succulents.",
    verified: true,
    helpful: 52,
  },
  {
    id: "rev-008",
    productName: "Echeveria Rosette Seed Mix",
    productSlug: "echeveria-seed-mix",
    rating: 4,
    customerName: "Priya N.",
    location: "San Jose, CA",
    date: "2025-11-20",
    title: "Beautiful rosettes forming",
    body: "About 200 tiny rosettes are now growing on my windowsill. The mix has good color variety — some pink-tipped, some blue-green, some almost purple. Germination took about 10 days which was longer than I expected but worth the wait. The heat mat recommendation in the guide made a big difference.",
    verified: true,
    helpful: 24,
  },
  {
    id: "rev-009",
    productName: "Jade Plant (Crassula ovata) Seeds",
    productSlug: "jade-plant-seeds",
    rating: 5,
    customerName: "Marcus B.",
    location: "Chicago, IL",
    date: "2025-08-30",
    title: "Incredibly easy — great starter plant",
    body: "If you're new to growing from seed, start here. Jade seeds are forgiving, germinate quickly, and the seedlings are tough. I've given several away as gifts. For the price this is an absolute steal. Great gateway into the cactus/succulent hobby.",
    verified: true,
    helpful: 31,
  },
  {
    id: "rev-010",
    productName: "Astrophytum (Star Cactus) Seeds",
    productSlug: "astrophytum-star-cactus",
    rating: 5,
    customerName: "Yuki S.",
    location: "San Francisco, CA",
    date: "2025-12-15",
    title: "Worth every penny for collectors",
    body: "These Astrophytum seeds are the real deal. Perfectly formed star-shaped seedlings emerging after just 8 days. I've been collecting Astrophytum for years and the genetics in this batch look exceptional. Limited stock warning is real — don't hesitate if you're considering these.",
    verified: true,
    helpful: 28,
  },
  {
    id: "rev-011",
    productName: "Aztekium ritteri Seeds",
    productSlug: "aztekium-ritteri",
    rating: 5,
    customerName: "Carlos R.",
    location: "El Paso, TX",
    date: "2025-10-28",
    title: "The patience plant — but worth it",
    body: "These are notoriously slow growers but the seeds are viable and the germination was decent. I'm 6 months in and they're finally looking like actual Aztekium. If you understand what you're getting into — a years-long project — these seeds are excellent. The seller clearly knows their stuff.",
    verified: true,
    helpful: 19,
  },
  {
    id: "rev-012",
    productName: "Blossfeldia liliputana (Smallest Cactus) Seeds",
    productSlug: "blossfeldia-lliputana",
    rating: 5,
    customerName: "Ingrid F.",
    location: "Minneapolis, MN",
    date: "2025-11-05",
    title: "The world's tiniest cactus — and it's real",
    body: "I collect miniature plants and this is the crown jewel. The seeds are absurdly small but I got several to germinate. They're now the size of a peppercorn and I love them. The packaging included a magnifying glass tip card which I thought was a nice touch. Truly a specialty product.",
    verified: true,
    helpful: 35,
  },
  {
    id: "rev-013",
    productName: "Seedling Heat Mat (10x20 inch)",
    productSlug: "seedling-heat-mat",
    rating: 4,
    customerName: "Alex D.",
    location: "Nashville, TN",
    date: "2025-09-12",
    title: "Solid heat mat, good temperature",
    body: "Keeps my seed trays at a consistent 78°F which is exactly what I needed for germination. The mat is sturdy and the waterproof surface is easy to clean. Only 4 stars because the cord could be a bit longer — had to rearrange my setup to reach the outlet. But the product itself works great.",
    verified: true,
    helpful: 15,
  },
  {
    id: "rev-014",
    productName: "Deluxe Seed Germination Kit",
    productSlug: "germination-kit",
    rating: 5,
    customerName: "Nina V.",
    location: "Miami, FL",
    date: "2025-12-01",
    title: "Everything you need in one box",
    body: "Bought this as a gift for my partner who wanted to start growing cacti. The kit has everything — trays, dome, soil mix, seeds, instructions. No trips to the hardware store needed. The quality of the trays is noticeably better than the cheap ones at garden centers. Already planning to order individual refills.",
    verified: true,
    helpful: 22,
  },
  {
    id: "rev-015",
    productName: "Premium Succulent & Cactus Soil Mix",
    productSlug: "succulent-soil-mix",
    rating: 5,
    customerName: "Jordan P.",
    location: "Raleigh, NC",
    date: "2025-10-19",
    title: "Perfect drainage, no more root rot",
    body: "Switched from regular potting soil to this mix and the difference was immediate. My succulents stopped getting mushy and the cacti roots are actually developing properly. The perlite-to-organic ratio seems spot on. One bag lasted me about 40 small pots. Great value.",
    verified: true,
    helpful: 27,
  },
  {
    id: "rev-016",
    productName: "Precision Planting Tweezers Set",
    productSlug: "tweezers-set",
    rating: 4,
    customerName: "Laura C.",
    location: "Boston, MA",
    date: "2025-11-25",
    title: "Handy for tiny seeds",
    body: "These tweezers make handling lithops and astrophytum seeds SO much easier. The curved tip is perfect for placing seeds on soil without burying them. The set includes three different tips which covers all use cases. Wish they came in a nicer case, but the tools themselves are well-made.",
    verified: true,
    helpful: 12,
  },
  {
    id: "rev-017",
    productName: "Saguaro (Carnegiea gigantea) Seed Pack",
    productSlug: "saguaro-seed-pack",
    rating: 5,
    customerName: "Henry T.",
    location: "Albuquerque, NM",
    date: "2025-12-18",
    title: "Authentic desert genetics",
    body: "As someone who grew up in the Sonoran Desert, I can tell these seeds are the real deal. The saguaro seedlings look exactly like the ones I've seen sprouting after monsoon rains. Shipped fast and the germination exceeded my expectations. These guys know their cacti.",
    verified: true,
    helpful: 39,
  },
  {
    id: "rev-018",
    productName: "San Pedro (Trichocereus pachanoi) Seeds",
    productSlug: "san-pedro-seed-pack",
    rating: 4,
    customerName: "Ryan M.",
    location: "Flagstaff, AZ",
    date: "2025-09-30",
    title: "Good seeds, solid germination",
    body: "Got about 80% germination on these San Pedro seeds. The seedlings are now about 2 inches tall and growing fast. The only reason for 4 stars is I wish the pack had more seeds — I went through them quickly. But quality-wise no complaints at all.",
    verified: true,
    helpful: 16,
  },
  {
    id: "rev-019",
    productName: "Lithops (Living Stones) Mixed Seeds",
    productSlug: "lithops-living-stones",
    rating: 5,
    customerName: "Emma W.",
    location: "Denver, CO",
    date: "2025-12-20",
    title: "Addictive hobby warning",
    body: "I bought one pack of lithops seeds as a curiosity. Now I have 15 pots of different lithops varieties and I'm planning a whole windowsill dedicated to them. These seeds germinated beautifully and the variety in the mix is impressive. If you like unusual plants, this is your gateway drug.",
    verified: true,
    helpful: 44,
  },
  {
    id: "rev-020",
    productName: "Echeveria Rosette Seed Mix",
    productSlug: "echeveria-seed-mix",
    rating: 5,
    customerName: "Olivia K.",
    location: "Portland, OR",
    date: "2025-11-08",
    title: "Stunning color variety",
    body: "I wasn't expecting much from seed-grown echeveria but these completely surprised me. The color variation in the mix is gorgeous — lavender edges, peach tips, deep jade centers. They look like living jewels. Combined with the premium soil mix from the same shop, these are thriving.",
    verified: true,
    helpful: 30,
  },
];

export function getAverageRating(): number {
  if (reviews.length === 0) return 0;
  const sum = reviews.reduce((acc, r) => acc + r.rating, 0);
  return Math.round((sum / reviews.length) * 10) / 10;
}

export function getRatingDistribution(): Record<number, number> {
  const dist: Record<number, number> = { 1: 0, 2: 0, 3: 0, 4: 0, 5: 0 };
  for (const r of reviews) {
    dist[r.rating] = (dist[r.rating] || 0) + 1;
  }
  return dist;
}

export function getReviewsForProduct(slug: string): Review[] {
  return reviews.filter((r) => r.productSlug === slug);
}
