export interface Review {
  id: string;
  productName: string;
  productSlug: string;
  rating: number;
  customerName: string;
  location: string;
  date: string;
  title: string;
  body: string;
  verified: boolean;
  helpful: number;
}

export const reviews: Review[] = [
  {
    id: "rev-001",
    productName: "German Shepherd",
    productSlug: "german-shepherd",
    rating: 5,
    customerName: "Maria G.",
    location: "Phoenix, AZ",
    date: "2026-01-14",
    title: "A confident and loyal companion",
    body: "Our German Shepherd was healthy, well-socialized, and came with complete vet records. The team answered every question we had before pickup and sent photos along the way. He's now 6 months old, sharp as a tack, and the best family protector you could ask for.",
    verified: true,
    helpful: 47,
  },
  {
    id: "rev-002",
    productName: "Golden Retriever",
    productSlug: "golden-retriever",
    rating: 5,
    customerName: "Daniel K.",
    location: "Austin, TX",
    date: "2025-12-20",
    title: "The happiest puppy in Texas",
    body: "Our Golden came home calm, curious, and already used to being handled. The free starter guide was genuinely useful. She's now crate-trained and fetching everything that moves. You can tell these folks raise their puppies with love.",
    verified: true,
    helpful: 38,
  },
  {
    id: "rev-003",
    productName: "French Bulldog",
    productSlug: "french-bulldog",
    rating: 5,
    customerName: "Elijah W.",
    location: "Denver, CO",
    date: "2026-01-05",
    title: "A perfect apartment companion",
    body: "Our Frenchie is a little bundle of charm. He was fully vaccinated and came with health papers, and the team was incredibly transparent about his lineage. He settled into apartment life in days. Couldn't be happier.",
    verified: true,
    helpful: 31,
  },
  {
    id: "rev-004",
    productName: "Siamese",
    productSlug: "siamese",
    rating: 5,
    customerName: "Sarah L.",
    location: "Tucson, AZ",
    date: "2025-11-18",
    title: "Talkative, loving, and healthy",
    body: "Our Siamese kitten was litter trained from day one and already knew her name. She's the chattiest, most affectionate cat I've ever owned. The adoption process was smooth and the health records were thorough. 10/10.",
    verified: true,
    helpful: 24,
  },
  {
    id: "rev-005",
    productName: "Maine Coon",
    productSlug: "maine-coon",
    rating: 5,
    customerName: "Rebecca T.",
    location: "Portland, OR",
    date: "2025-12-01",
    title: "A giant ball of fluff and love",
    body: "Our Maine Coon kitten has the sweetest temperament and the fluffiest ear tufts. He's growing fast and loves following us around. The store kept in touch after delivery to check how he was settling in. Great service.",
    verified: true,
    helpful: 33,
  },
  {
    id: "rev-006",
    productName: "Holland Lop",
    productSlug: "holland-lop",
    rating: 5,
    customerName: "Jess M.",
    location: "Brooklyn, NY",
    date: "2025-12-10",
    title: "The cutest thing on four paws",
    body: "Our Holland Lop is gentle, curious, and totally litter-trained already. He free-roams our apartment and hops over for pets constantly. The care sheet they include answered everything we needed as first-time bunny owners.",
    verified: true,
    helpful: 29,
  },
  {
    id: "rev-007",
    productName: "Lionhead",
    productSlug: "lionhead",
    rating: 5,
    customerName: "Tom H.",
    location: "Seattle, WA",
    date: "2025-11-25",
    title: "A fluffy little lion",
    body: "Our Lionhead has the most ridiculous, adorable mane. He's outgoing and loves the whole family. Delivery was well arranged and he arrived calm and healthy. Would absolutely order from here again.",
    verified: true,
    helpful: 18,
  },
  {
    id: "rev-008",
    productName: "African Grey Parrot",
    productSlug: "african-grey",
    rating: 5,
    customerName: "Priya N.",
    location: "San Jose, CA",
    date: "2026-01-08",
    title: "Unbelievably intelligent bird",
    body: "Our African Grey came hand-raised, calm, and already talking a little. The avian health check paperwork was comprehensive. He's bonded deeply with our family and his vocabulary is growing weekly. Worth every penny.",
    verified: true,
    helpful: 42,
  },
  {
    id: "rev-009",
    productName: "Cockatiel",
    productSlug: "cockatiel",
    rating: 5,
    customerName: "Marcus B.",
    location: "Chicago, IL",
    date: "2025-10-30",
    title: "A whistling sweetheart",
    body: "Our Cockatiel is gentle, calm, and already whistling his favorite tunes. The store's follow-up call to make sure he was eating well was a really nice touch. Perfect first bird for anyone.",
    verified: true,
    helpful: 22,
  },
  {
    id: "rev-010",
    productName: "Betta Fish",
    productSlug: "betta",
    rating: 5,
    customerName: "Yuki S.",
    location: "San Francisco, CA",
    date: "2025-12-15",
    title: "Arrived vibrant and healthy",
    body: "Packaging was excellent — stable temperature, plenty of water, and he arrived flaring and full of energy. He's now living in a planted tank and has the most stunning red-and-blue coloring. Great acclimation guide included.",
    verified: true,
    helpful: 20,
  },
  {
    id: "rev-011",
    productName: "Neon Tetra",
    productSlug: "neon-tetra",
    rating: 5,
    customerName: "Carlos R.",
    location: "El Paso, TX",
    date: "2025-11-02",
    title: "Zero losses on arrival",
    body: "Ordered a school of neon tetras and every single one arrived alive and active. They've colored up beautifully in the planted tank. You can tell they take shipping seriously. Highly recommend.",
    verified: true,
    helpful: 16,
  },
  {
    id: "rev-012",
    productName: "Cherry Shrimp",
    productSlug: "cherry-shrimp",
    rating: 5,
    customerName: "Ingrid F.",
    location: "Minneapolis, MN",
    date: "2025-12-05",
    title: "Gorgeous red colony starters",
    body: "Bought 10 cherry shrimp and they arrived healthy with the vivid red I was hoping for. They were breeding within a month. Now I have a booming colony. Great communication and fast, careful shipping.",
    verified: true,
    helpful: 27,
  },
  {
    id: "rev-013",
    productName: "Clownfish",
    productSlug: "clownfish",
    rating: 5,
    customerName: "Alex D.",
    location: "Nashville, TN",
    date: "2025-12-22",
    title: "Healthy, hardy reef fish",
    body: "My pair of clownfish arrived in perfect shape and took to the anemone immediately. They eat from my hand now. The acclimation guide they include is spot-on and saved me from rookie mistakes. Outstanding saltwater supplier.",
    verified: true,
    helpful: 35,
  },
  {
    id: "rev-014",
    productName: "Bearded Dragon",
    productSlug: "bearded-dragon",
    rating: 5,
    customerName: "Nina V.",
    location: "Miami, FL",
    date: "2026-01-02",
    title: "A gentle, funny little dinosaur",
    body: "Our beardie arrived healthy, alert, and already well-socialized. He waves at us, loves his dubia roaches, and enjoys daily baths. The enclosure guide that came with him was genuinely comprehensive.",
    verified: true,
    helpful: 30,
  },
  {
    id: "rev-015",
    productName: "Leopard Gecko",
    productSlug: "leopard-gecko",
    rating: 5,
    customerName: "Jordan P.",
    location: "Raleigh, NC",
    date: "2025-11-15",
    title: "Docile and stunning",
    body: "Our leopard gecko has a gorgeous morph and the calmest temperament — he's never once tried to bite. Handled shipping stress beautifully and eats like a champ. Perfect beginner gecko from a supplier that knows their stuff.",
    verified: true,
    helpful: 19,
  },
  {
    id: "rev-016",
    productName: "Ball Python",
    productSlug: "ball-python",
    rating: 5,
    customerName: "Laura C.",
    location: "Boston, MA",
    date: "2025-12-12",
    title: "Calm, healthy, and eating well",
    body: "The ball python we received was in perfect condition with clear paperwork and a clean health certificate. She's eaten at every feeding since and lets everyone handle her. Great, honest seller with fast replies.",
    verified: true,
    helpful: 14,
  },
  {
    id: "rev-017",
    productName: "Corn Snake",
    productSlug: "corn-snake",
    rating: 4,
    customerName: "Henry T.",
    location: "Albuquerque, NM",
    date: "2025-12-18",
    title: "A beautiful first snake",
    body: "Our corn snake arrived healthy and has a stunning amelanistic pattern. Super easy to care for and great with handling. Only reason for 4 stars is I wish there were more substrate samples included — minor thing. Would buy from them again.",
    verified: true,
    helpful: 11,
  },
  {
    id: "rev-018",
    productName: "Russian Tortoise",
    productSlug: "russian-tortoise",
    rating: 5,
    customerName: "Ryan M.",
    location: "Flagstaff, AZ",
    date: "2025-11-29",
    title: "An active little tank",
    body: "Our Russian tortoise is full of personality — she bulldozes her enclosure and loves her dandelion greens. Arrived healthy with a great care guide. The team even checked in a week later. Wonderful experience.",
    verified: true,
    helpful: 23,
  },
  {
    id: "rev-019",
    productName: "Sulcata Tortoise",
    productSlug: "sulcata-tortoise",
    rating: 5,
    customerName: "Emma W.",
    location: "Denver, CO",
    date: "2025-12-20",
    title: "Slow, steady, and adorable",
    body: "Our sulcata hatchling is thriving. He came with detailed setup advice because these guys get huge — the team was upfront about adult size and space needs, which I appreciated. Healthy appetite and already growing.",
    verified: true,
    helpful: 17,
  },
  {
    id: "rev-020",
    productName: "Sun Conure",
    productSlug: "sun-conure",
    rating: 5,
    customerName: "Olivia K.",
    location: "Portland, OR",
    date: "2025-11-08",
    title: "A rainbow of pure joy",
    body: "Our Sun Conure is a ball of sunshine — vivid colors, endless energy, and so affectionate. Hand-raised and socialized exactly as advertised. The store was wonderful about answering my many, many questions.",
    verified: true,
    helpful: 26,
  },
];

export function getAverageRating(): number {
  if (reviews.length === 0) return 0;
  const sum = reviews.reduce((acc, r) => acc + r.rating, 0);
  return Math.round((sum / reviews.length) * 10) / 10;
}

export function getRatingDistribution(): Record<number, number> {
  const dist: Record<number, number> = { 1: 0, 2: 0, 3: 0, 4: 0, 5: 0 };
  for (const r of reviews) {
    dist[r.rating] = (dist[r.rating] || 0) + 1;
  }
  return dist;
}

export function getReviewsForProduct(slug: string): Review[] {
  return reviews.filter((r) => r.productSlug === slug);
}